# Generated by Django 2.2.5 on 2019-09-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20190909_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='系统编号'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_link',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='生产线'),
        ),
    ]
